### ISSUE TITLE
Stylization

### ISSUE THREAD

**Issue by RustyPotato** [chocolatemelt/fe-cli#16]
I'm just a visitor for now, however, glancing over the code I notice several points of interest: 

- Tabs vs Spaces. A very contested issue the world over. Basically, choose one and stick with it. 
- It is good that there are multiple files for different parts, but make sure that most of the files have some sort of description at the top saying what they do/where they fit in. (either in the cpp or h). 
- Perhaps include a file of to do action items or some record of what is being worked on currently and what is in the pipeline for later on. (Quite possibly just a list of projects for large ideas and issues for small things leading up to the projects).

**Comment by chocolatemelt** [comment]
yeah, the tabs vs spaces thing is a weird side effect of people's editors forcing defaults - will definitely get that set in stone soon, since it's a big issue for files where they're suddenly mixed.

i think i'll be adding some descriptions to class files soon, but as of now a lot of them are still just prototypes. was thinking of updating the file documentation in general anyway to be more human-readable.

for now, i've just been using the issues tracker on gh to monitor what's going on, but a file inside the repository might be a good way to do that as well

thanks for the checkup though, super appreciated

**Comment by RustyPotato** [comment]
I believe that this commit (fad19ec5e9ed6dd83592812af78dcc5fc73b3a97) will have cleared this issue up. If you agree, feel free to close this. If you think there is more, leave it open.
